// <auto-generated />
using CarNumberGuideApp.RDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarNumberGuideApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240712114432_Db-Entities2")]
    partial class DbEntities2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarNumberGuideApp.RDB.DbEntities.DbRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("CarNumberGuideApp.RDB.DbEntities.DbRegionNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("RegionNumbers");
                });

            modelBuilder.Entity("CarNumberGuideApp.RDB.DbEntities.DbRegistrationNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RegionNumberId")
                        .HasColumnType("int");

                    b.Property<string>("SymbolicCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegionNumberId");

                    b.ToTable("RegistrationNumbers");
                });

            modelBuilder.Entity("CarNumberGuideApp.RDB.DbEntities.DbRegionNumber", b =>
                {
                    b.HasOne("CarNumberGuideApp.RDB.DbEntities.DbRegion", "Region")
                        .WithMany("RegionNumbers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("CarNumberGuideApp.RDB.DbEntities.DbRegistrationNumber", b =>
                {
                    b.HasOne("CarNumberGuideApp.RDB.DbEntities.DbRegionNumber", "RegionNumber")
                        .WithMany("RegistrationNumbers")
                        .HasForeignKey("RegionNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionNumber");
                });

            modelBuilder.Entity("CarNumberGuideApp.RDB.DbEntities.DbRegion", b =>
                {
                    b.Navigation("RegionNumbers");
                });

            modelBuilder.Entity("CarNumberGuideApp.RDB.DbEntities.DbRegionNumber", b =>
                {
                    b.Navigation("RegistrationNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
